/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { Desktop1Props } from 'src/types';

const Desktop11: any = styled('div')({
  backgroundColor: `rgba(13, 0, 0, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Soon: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `30px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `685px`,
  top: `476px`,
});

const ExternalLink: any = styled('a')({
  width: `100%`,
  textDecoration: `none`,
});

const Rectangle1: any = styled('div')({
  backgroundColor: `rgba(16, 198, 255, 1)`,
  width: `299px`,
  height: `52px`,
  position: `absolute`,
  left: `570px`,
  top: `528px`,
});

const ExternalLink1: any = styled('a')({
  width: `299px`,
  textDecoration: `none`,
});

function Desktop1(props: Desktop1Props): JSX.Element {
  return (
    <Desktop11>
      <ExternalLink href="https://google.com">
        <Soon>{`soon`}</Soon>
      </ExternalLink>
      <ExternalLink1 href="http://youtube.com">
        <Rectangle1></Rectangle1>
      </ExternalLink1>
    </Desktop11>
  );
}

export default Desktop1;
