/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { MyWebsiteProps } from 'src/types';

const MyWebsite1: any = styled('div')({
  backgroundColor: `rgba(15, 0, 0, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle1: any = styled('div')({
  backgroundColor: `rgba(255, 0, 0, 1)`,
  width: `420px`,
  height: `74px`,
  position: `absolute`,
  left: `529px`,
  top: `536px`,
});

const Test: any = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Inter`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `302px`,
  top: `273px`,
});

function MyWebsite(props: MyWebsiteProps): JSX.Element {
  return (
    <MyWebsite1>
      <Rectangle1></Rectangle1>
      <Test>{`Test`}</Test>
    </MyWebsite1>
  );
}

export default MyWebsite;
